parameters:
  DocsCiConfig: not-set

jobs:
  - job: CreateDocIndex
    pool:
      vmImage: windows-2019

    variables:
      DocsMsRepoLocation: $(Pipeline.Workspace)/docsms

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.6'
        inputs:
          versionSpec: '3.6'

      # - pwsh: |
      #     Invoke-WebRequest -Uri "https://github.com/dotnet/docfx/releases/download/v2.43.2/docfx.zip" `
      #     -OutFile "docfx.zip" | Wait-Process; Expand-Archive -Path "docfx.zip" -DestinationPath ./docfx
      #     echo "##vso[task.setvariable variable=docfxPath]$(Build.BinariesDirectory)/docfx/docfx.exe"
      #   workingDirectory: $(Build.BinariesDirectory)
      #   displayName: Download and Extract DocFX

      # - task: PowerShell@2
      #   displayName: 'Generate Doc Index'
      #   inputs:
      #     pwsh: true
      #     filePath: $(Build.SourcesDirectory)/eng/common/docgeneration/Generate-DocIndex.ps1 
      #     arguments: >
      #       -Docfx $(docfxPath)
      #       -RepoRoot $(Build.SourcesDirectory)
      #       -DocGenDir "$(Build.SourcesDirectory)/eng/common/docgeneration"
      #       -DocOutDir "$(Build.ArtifactStagingDirectory)/docfx_project"
      #       -verbose

      # - task: UsePythonVersion@0
      #   displayName: 'Use Python 3.6'
      #   inputs:
      #     versionSpec: '3.6'
      # - template: /eng/common/pipelines/templates/steps/mashup-doc-index.yml
      #   parameters:
      #     SourceDirectory: $(Build.ArtifactStagingDirectory)
      # - pwsh: |
      #     Copy-Item -Path $(Build.SourcesDirectory)/eng/* -Destination ./ -Recurse -Force
      #     echo "##vso[task.setvariable variable=toolPath]$(Build.BinariesDirectory)"
      #   workingDirectory: $(Build.BinariesDirectory)
      #   displayName: Move eng/common to Tool Directory   

      # - task: PublishPipelineArtifact@0
      #   condition: succeeded()
      #   inputs:
      #     artifactName: "Doc.Index"
      #     targetPath: $(Build.ArtifactStagingDirectory)/docfx_project/_site
          
      # - pwsh: |
      #     git checkout -b gh-pages-local --track origin/gh-pages-root -f
      #   workingDirectory: $(Build.SourcesDirectory)
      #   displayName: Git pull GH pages branch

      # - pwsh: |
      #     Copy-Item -Path $(Build.ArtifactStagingDirectory)/docfx_project/_site/* -Destination ./ -Recurse -Force
      #     git add -A
      #   workingDirectory: $(Build.SourcesDirectory)
      #   displayName: Copy the latest changes

      # - task: PowerShell@2
      #   displayName: Push the Docs to GH-Pages
      #   condition: succeeded()
      #   inputs:
      #     pwsh: true
      #     workingDirectory: $(Build.SourcesDirectory)
      #     filePath: $(toolPath)/common/scripts/git-branch-push.ps1
      #     arguments: >
      #       -PRBranchName "gh-pages"
      #       -CommitMsg "Auto-generated docs from SHA(s) $(Build.SourceVersion)"
      #       -GitUrl "https://$(azuresdk-github-pat)@github.com/$(Build.Repository.Name).git"
      #       -PushArgs "--force"

      - pwsh: |
          Write-Host "git clone https://github.com/MicrosoftDocs/azure-docs-sdk-node.git $(DocsMsRepoLocation)"
          git clone https://github.com/MicrosoftDocs/azure-docs-sdk-node.git $(DocsMsRepoLocation)
        displayName: Clone Docs.ms Repository
        ignoreLASTEXITCODE: false

      - task: PowerShell@2
        displayName: Update Docs.MS CI Targeted Packages
        inputs:
          targetType: filePath
          filePath: eng/common/scripts/update-docs-ci.ps1
          arguments: >
            -DocRepoLocation $(DocsMsRepoLocation)
            -Configs ${{ parameters.DocsCiConfig }}
          pwsh: true
        env:
          GH_TOKEN: $(azuresdk-github-pat)

      - template: /eng/common/pipelines/templates/steps/set-default-branch.yml
        parameters:
          WorkingDirectory: $(DocsMsRepoLocation)
          OutputVariableName: DocsMsRepoLocationDefaultBranch

      - template: /eng/common/pipelines/templates/steps/git-push-changes.yml
        parameters:
          BaseRepoBranch: $(DocsMsRepoLocationDefaultBranch)
          BaseRepoOwner: 'MicrosoftDocs'
          CommitMsg: "Update targeting packages based on release csv."
          TargetRepoName: 'azure-docs-sdk-node'
          TargetRepoOwner: 'MicrosoftDocs'
          WorkingDirectory: $(DocsMsRepoLocation)
          ScriptDirectory: $(Build.SourcesDirectory)/eng/common/scripts

      # Prepare daily docs CI
      # This instance of the branch may be behind the default branch w/r/t the
      # list of published packages
      # TODO: Should we scan the repo for packages to onboard ahead of 
      # publishing?
      - pwsh: |
          $branchName = "daily/$(Get-Date -Format 'yyyy-MM-dd')"
          Write-Host "Daily Branch Name: $branchName"
          Write-Host "##vso[task.setvariable variable=DailyDocsBranchName;]$branchName"
        displayName: Set daily docs branch name

      - pwsh: |
          $ErrorActionPreference = "Continue"
          git checkout "origin/$(DailyDocsBranchName)" 2>&1 | Out-Null
          $LASTEXITCODE = 0 # This ignores any error from git checkout
          git status
        displayName: Checkout daily branch if it exists
        workingDirectory: $(DocsMsRepoLocation)

      - task: PowerShell@2
        displayName: Update Docs.MS CI Targeted Packages
        inputs:
          targetType: filePath
          filePath: eng/common/scripts/update-docs-ci.ps1
          arguments: >
            -DocRepoLocation $(DocsMsRepoLocation)
            -Configs ${{ parameters.DocsCiConfig }}
            -UseDailyDocsVersion
          pwsh: true
        env:
          GH_TOKEN: $(azuresdk-github-pat)

      - template: /eng/common/pipelines/templates/steps/git-push-changes.yml
        parameters:
          BaseRepoBranch: $(DailyDocsBranchName)
          BaseRepoOwner: 'MicrosoftDocs'
          CommitMsg: "Update targeting packages based on release csv. (Daily docs)"
          TargetRepoName: 'azure-docs-sdk-node'
          TargetRepoOwner: 'MicrosoftDocs'
          WorkingDirectory: $(DocsMsRepoLocation)
          ScriptDirectory: $(Build.SourcesDirectory)/eng/common/scripts
